In [1]:
import pandas as pd
import prep_plays
pd.set_option('display.max_columns', None)

Acquire.py Loaded Successfully
Prep.py Loaded Successfully

In [2]:
df = prep_plays.prep_plays_data()

In [3]:
df.shape

(17007, 57)

In [4]:
df.isnull().sum()

playDescription            0
quarter                    0
down                       0
yardsToGo                  0
possessionTeam             0
offenseFormation          77
defendersInTheBox          0
numberOfPassRushers        0
typeDropback               6
gameClock                  6
absoluteYardlineNumber     6
epa                        0
RB                         0
TE                         0
WR                         0
DL                         0
LB                         0
DB                         0
ARI                        0
ATL                        0
BAL                        0
BUF                        0
CAR                        0
CHI                        0
CIN                        0
CLE                        0
DAL                        0
DEN                        0
DET                        0
GB                         0
HOU                        0
IND                        0
JAX                        0
KC                         0
LA                         0
LAC                        0
MIA                        0
MIN                        0
NE                         0
NO                         0
NYG                        0
NYJ                        0
OAK                        0
PHI                        0
PIT                        0
SEA                        0
SF                         0
TB                         0
TEN                        0
WAS                        0
EMPTY                      0
I_FORM                     0
JUMBO                      0
PISTOL                     0
SHOTGUN                    0
SINGLEBACK                 0
WILDCAT                    0
dtype: int64

In [5]:
df.head()

,playDescription,quarter,down,yardsToGo,possessionTeam,offenseFormation,defendersInTheBox,numberOfPassRushers,typeDropback,gameClock,absoluteYardlineNumber,epa,RB,TE,WR,DL,LB,DB,ARI,ATL,BAL,BUF,CAR,CHI,CIN,CLE,DAL,DEN,DET,GB,HOU,IND,JAX,KC,LA,LAC,MIA,MIN,NE,NO,NYG,NYJ,OAK,PHI,PIT,SEA,SF,TB,TEN,WAS,EMPTY,I_FORM,JUMBO,PISTOL,SHOTGUN,SINGLEBACK,WILDCAT
0,(15:00) M.Ryan pass short right to J.Jones pus...,1,1,15,ATL,I_FORM,7.0,4.0,TRADITIONAL,15:00:00,90.0,0.261827,2,1,2,4,2,5,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
1,(13:10) M.Ryan pass incomplete short right to ...,1,1,10,ATL,SINGLEBACK,7.0,4.0,TRADITIONAL,13:10:00,49.0,-0.372360,1,1,3,4,2,5,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
2,(13:05) (Shotgun) M.Ryan pass incomplete short...,1,2,10,ATL,SHOTGUN,6.0,4.0,TRADITIONAL,13:05:00,49.0,-0.702779,2,1,2,4,2,5,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,(13:01) (Shotgun) M.Ryan pass deep left to J.J...,1,3,10,ATL,SHOTGUN,6.0,5.0,SCRAMBLE_ROLLOUT_LEFT,13:01:00,49.0,3.047530,1,1,3,4,1,6,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
4,(10:59) (Shotgun) M.Ryan pass incomplete short...,1,3,1,ATL,SHOTGUN,8.0,6.0,TRADITIONAL,10:59:00,11.0,-0.842272,2,3,0,6,3,2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0

In [6]:
df.offenseFormation.value_counts()

SHOTGUN       11291
SINGLEBACK     2412
EMPTY          2203
I_FORM          794
PISTOL          213
JUMBO            14
WILDCAT           3
Name: offenseFormation, dtype: int64